/*1. What are the names of all the countries in the country table?*/

SELECT country_name
FROM country;

/*2. What is the total number of customers in the customers table?*/

SELECT COUNT(DISTINCT customer_id) 
	AS total_customer_number
FROM customers;

/*3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?*/

SELECT can_email, 
	ROUND(AVG(age),2) AS average_age
FROM customers
WHERE can_email = 'yes';

/*4. How many orders were made by customers aged 30 or older?*/

SELECT COUNT(o.order_id) AS total_order_made
FROM orders o
	INNER JOIN customers c USING(customer_id)
WHERE c.age >= 30;

/*5. What is the total revenue generated by each product category?*/

SELECT p.category, 
	SUM(p.price) AS total_reveue
FROM products p
	JOIN baskets b USING(product_id)
GROUP BY p.category;

/*6. What is the average price of products in the 'food' category?*/

SELECT category, 
	ROUND(AVG(price),2) AS average_price
FROM products
WHERE category = 'food';

/*7. How many orders were made in each sales channel (sales_channel column) in the orders table?*/

SELECT sales_channel,
	COUNT(*) AS total_order_made
FROM orders
GROUP BY sales_channel;

/*8.What is the date of the latest order made by a customer who can receive marketing emails?*/

SELECT o.date_shop
FROM customers c
	JOIN orders o USING(customer_id)
WHERE c.can_email = 'yes'
ORDER BY o.date_shop DESC
LIMIT 1;

/*9. What is the name of the country with the highest number of orders?*/

SELECT c.country_name, 
	COUNT(*) AS highest_order
FROM orders o
	JOIN country c USING(country_id)
GROUP BY c.country_name
ORDER BY COUNT(*) DESC
LIMIT 1;

/*10. What is the average age of customers who made orders in the 'vitamins' product category?*/

SELECT p.category, 
	ROUND(AVG(c.age),2) AS average_age
FROM orders o
	JOIN customers c USING(customer_id)
    JOIN baskets b USING(order_id)
    JOIN products p USING(product_id)
WHERE p.category = 'vitamins';

